# Generated by Django 4.0.6 on 2022-07-26 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='date_reeita',
            new_name='date_receita',
        ),
    ]
